// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZs5mzFIV4Vp96R4BUy1kfylVLszjedE',
    appId: '1:109805810153:web:aeec0ae14a86100a361b78',
    messagingSenderId: '109805810153',
    projectId: 'usiiname-push-notification',
    authDomain: 'usiiname-push-notification.firebaseapp.com',
    storageBucket: 'usiiname-push-notification.appspot.com',
    measurementId: 'G-8V8Z8SV718',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMreaWygvMS0l7Drb50eBrK7TOUDaUa0Q',
    appId: '1:109805810153:android:82e370a0d1b72cd6361b78',
    messagingSenderId: '109805810153',
    projectId: 'usiiname-push-notification',
    storageBucket: 'usiiname-push-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLlfTwwPIP9WlpboSPuHSpC3ecueB9jk',
    appId: '1:109805810153:ios:08f0beebd43a21f6361b78',
    messagingSenderId: '109805810153',
    projectId: 'usiiname-push-notification',
    storageBucket: 'usiiname-push-notification.appspot.com',
    iosBundleId: 'com.example.usiiname',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGLlfTwwPIP9WlpboSPuHSpC3ecueB9jk',
    appId: '1:109805810153:ios:a942932444b13da3361b78',
    messagingSenderId: '109805810153',
    projectId: 'usiiname-push-notification',
    storageBucket: 'usiiname-push-notification.appspot.com',
    iosBundleId: 'com.example.usiiname.RunnerTests',
  );
}
